# Generated by Django 2.2 on 2020-02-03 01:02
import csv
import os

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, transaction


@transaction.atomic
def migracion_datos_inicial(apps, schema_editor):
    """
    Función para inicializar los datos de pais, ciudad, barrios
    :param apps:
    :param schema_editor:
    :return:
    """
    signo = apps.get_model('videocollect', 'Signo')

    ubicacion_archivo = os.path.abspath(os.path.join(
        os.path.dirname(__file__), '../../utils/migration_files')) + '/megals_export_ls.csv'
    with open(ubicacion_archivo) as archivo_csv:
        reader = csv.DictReader(archivo_csv)
        for i, row in enumerate(reader):
            signo.objects.create(nombre=row['name'], video=row['url'])


@transaction.atomic
def reverse(apps, schema_editor):
    """
    Función para revertir el migrate
    :param apps:
    :param schema_editor:
    :return:
    """
    signo = apps.get_model('videocollect', 'Signo')
    signo.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('videocollect', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migracion_datos_inicial, reverse)
    ]


