# Generated by Django 2.2.9 on 2020-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocollect', '0002_auto_20200203_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoentrenamiento',
            name='video_entrenamiento',
            field=models.URLField(),
        ),
    ]
