# Generated by Django 2.2.9 on 2020-02-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocollect', '0003_auto_20200208_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoentrenamiento',
            name='video_entrenamiento',
            field=models.URLField(blank=True),
        ),
    ]
